version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    network_mode: "host"
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: localhost
            port: 3306
            user: root
            password: ''
            database: prisma_album_api
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~